[package]
name = "ssg"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.68"
article = { path = "../article" }
clap = { version = "4.1.4", features = ["derive"] }
serde = "1.0.152"
tera = { version = "1.17.1", default-features = false }
