[package]
name = "ssg"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.65"
article = { path = "../article" }
clap = { version = "3.2.21", features = ["derive"] }
serde = "1.0.144"
tera = { version = "1.17.0", default-features = false }
