[package]
name = "ssg"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.69"
article = { path = "../article" }
clap = { version = "4.1.8", features = ["derive"] }
serde = "1.0.156"
tera = { version = "1.18.1", default-features = false }
