[package]
name = "ssg"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.70"
article = { path = "../article" }
clap = { version = "4.2.1", features = ["derive"] }
serde = "1.0.159"
tera = { version = "1.19.0", default-features = false }
