[package]
name = "ssg"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
article = { path = "../article" }
clap = { version = "4.0.18", features = ["derive"] }
serde = "1.0.147"
tera = { version = "1.17.1", default-features = false }
