[package]
name = "ssg"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.58"
article = { path = "../article" }
clap = { version = "3.2.16", features = ["derive"] }
serde = "1.0.141"
tera = { version = "1.16.0", default-features = false }
