[package]
name = "search"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.69"
article = { path = "../article" }
clap = { version = "4.1.9", features = ["derive"] }
lindera-tantivy = "0.18.0"
serde = "1.0.157"
tantivy = "0.18.1"
