[package]
name = "search"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.64"
article = { path = "../article" }
clap = { version = "3.2.17", features = ["derive"] }
lindera-tantivy = "0.13.3"
serde = "1.0.144"
tantivy = "0.17.0"
