[package]
name = "search"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
article = { path = "../article" }
clap = { version = "4.0.18", features = ["derive"] }
lindera-tantivy = "0.18.0"
serde = "1.0.147"
tantivy = "0.18.1"
