[package]
name = "search"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.65"
article = { path = "../article" }
clap = { version = "4.0.15", features = ["derive"] }
lindera-tantivy = "0.16.2"
serde = "1.0.145"
tantivy = "0.18.0"
