[package]
name = "search"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.70"
article = { path = "../article" }
clap = { version = "4.1.13", features = ["derive"] }
lindera-tantivy = "0.18.0"
serde = "1.0.158"
tantivy = "0.18.1"
