[package]
name = "search"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0.52"
lindera-tantivy = "0.8.1"
pulldown-cmark = "0.9.0"
serde = "1.0.133"
tantivy = "0.16.1"
yaml-front-matter = "0.1.0"
