---
- name: Check rust version
  shell:
    cmd: source ~/.cargo/env && rustc --version
    executable: /bin/bash
  register: rustc
  ignore_errors: yes

- when: rustc.rc != 0
  name: Fetch rustup
  uri:
    url: https://sh.rustup.rs
    return_content: yes
  register: rustup_installer

- when: rustc.rc != 0
  name: Run rustup installer
  become: true
  shell:
    cmd: sh -s -- -y
    stdin: "{{ rustup_installer.content }}"
