---
- name: Reload and enable firewall
  become: true
  ufw:
    state: enabled
    policy: deny

- name: Allow tcp access to port 80 (http)
  become: true
  ufw:
    rule: allow
    port: '80'
    proto: tcp

- name: Allow tcp access to port 443 (https)
  become: true
  ufw:
    rule: allow
    port: '443'
    proto: tcp

- name: Allow tcp access to port 22 (ssh)
  become: true
  ufw:
    rule: allow
    port: '22'
    proto: tcp
