[package]
name = "ssg"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.53"
article = { path = "../article" }
clap = { version = "3.0.10", features = ["derive"] }
serde = "1.0.134"
tera = { version = "1.15.0", default-features = false }
