[package]
name = "search"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.54"
article = { path = "../article" }
clap = { version = "3.1.1", features = ["derive"] }
lindera-tantivy = "0.8.1"
serde = "1.0.136"
tantivy = "0.16.1"
