[package]
name = "search"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.52"
article = { path = "../article" }
clap = { version = "3.0.10", features = ["derive"] }
lindera-tantivy = "0.8.1"
serde = "1.0.134"
tantivy = "0.16.1"
