[package]
name = "search"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.55"
article = { path = "../article" }
clap = { version = "3.1.3", features = ["derive"] }
lindera-tantivy = "0.10.0"
serde = "1.0.136"
tantivy = "0.16.1"
