[package]
name = "search"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.53"
article = { path = "../article" }
clap = { version = "3.0.12", features = ["derive"] }
lindera-tantivy = "0.8.1"
serde = "1.0.135"
tantivy = "0.16.1"
