[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-files = "0.6.1"
actix-rt = "1.1.1"
actix-web = { version = "4.0.1", features = ["openssl"] }
anyhow = "1.0.57"
env_logger = "0.9.0"
envy = "0.4.2"
futures = "0.3.21"
log = "0.4.17"
openssl = "0.10.40"
serde = "1.0.137"
